########################################################################################################################
##################################################***Check_mk Playbook***###############################################
## Source: https://gitlab.accor.net/kbenali/ansible/tree/master/Check_mk
## Ansible playbook for installing check_mk agnet on RHEL host
## handlers/mais.yml : manage xinetd service
##
########################################################################################################################
########################################################################################################################


- name: restart docker
  service:
    name: docker
    state: restarted
  become: yes

- name: restart docker-registy
  service:
    name: docker-distribution
    state: restarted
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
  become: yes

- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
