- name: Load docker images from archive
  docker_image:
    state: present
    name: "{{ item }}"
    load_path: "{{ install_tmp_path }}/{{ archive }}"
  when: ( groups['connected'][0] != groups['disconnected'][0] )


- name: Push images
  block:
    - docker_image:
        name: '{{ public_redhat_registry }}/{{ item }}:{{ ose_version_tag }}'
        tag: '{{ disconnected_registry_endpoint }}/{{ item }}:{{ ose_version_tag }}'
        load_path: "{{ install_tmp_path }}/{{ archive }}"
        state: present
      when: ( groups['connected'][0] != groups['disconnected'][0] )

    - docker_image:
        name: '{{ public_redhat_registry }}/{{ item }}:{{ ose_version_tag }}'
        tag: '{{ disconnected_registry_endpoint }}/{{ item }}:{{ ose_version_tag }}'
        state: present

    - docker_image:
        name: '{{ disconnected_registry_endpoint }}/{{ item }}:{{ ose_version_tag }}'
        push: yes
        pull: no

  rescue:
    - docker_image:
        name: '{{ public_redhat_registry }}/{{ item }}'
        state: present

    - shell: docker tag "{{ public_redhat_registry }}"/"{{ item }}" "{{ disconnected_registry_endpoint }}"/"{{ item }}":latest

    - debug:
        msg: "failed to pull image {{ item }} with tag : {{ ose_version_tag }}, pulled latest image !!"
