
- name: Pull images
  block:
    - docker_image:
        name: "{{ public_redhat_registry }}/{{ item }}:{{ ose_version_tag }}"
      register: image
#    - debug:
#        var: image

  rescue:
    - docker_image:
        name: "{{ public_redhat_registry }}/{{ item }}:latest"
      register: image
    - debug:
        msg: "failed to pull image {{ item }} with tag : {{ ose_version_tag }}, pulled latest image !!"
#    - debug:
#        var: image
  always:
    - name: Build a list of all the images.
      set_fact:
        images_list: '{{ images_list + " " + image.image.RepoTags[0] }}'
      when: image.image|selectattr("RepoTags", "defined")|list|length >0

    - name: Build a list of all the images (image exist).
      shell: docker image ls "{{ public_redhat_registry }}/{{ item }}" --format \{\{.Repository}}:\{\{.Tag\}\}
      register: docker_image
      when: image.image|selectattr("RepoTags", "undefined")

    - name: Build a list of all the images.
      set_fact:
        images_list: '{{ images_list + " " + docker_image.stdout }}'
      when: image.image|selectattr("RepoTags", "undefined")
